"""Gaia DR3 mission constants and VOTable export profile (mock/template stage).

Real Gaia epoch photometry will replace the mock provider internals later; this
module owns static PhotCal metadata and ``write_vo_lightcurve`` kwargs only.
"""

from __future__ import annotations

import logging

from skvo_veb.utils.lc_config import (
    JD_TO_MJD,
    PHOTCAL_KEY_EFFECTIVE_WAVELENGTH,
    PHOTCAL_KEY_EFFECTIVE_WAVELENGTH_UNIT,
    PHOTCAL_KEY_FILTER_IDENTIFIER,
    PHOTCAL_KEY_FILTER_NAME,
    PHOTCAL_KEY_MAG_SYS,
    PHOTCAL_KEY_ZP_FLUX,
    PHOTCAL_KEY_ZP_FLUX_UNIT,
    PHOTCAL_KEY_ZP_MAG,
    PHOTCAL_KEY_ZP_MAG_UNIT,
)
from skvo_veb.utils.my_tools import sanitize_filename

logger = logging.getLogger(__name__)

MISSION_ID = "gaia"

GAIA_TIMESCALE = "TCB"
GAIA_REFPOSITION = "BARYCENTER"
GAIA_PIPELINE = "Gaia DR3 (mock template)"
GAIA_SURVEY = "Gaia DR3"

GAIA_G_BAND = "G"
GAIA_G_FILTER_IDENTIFIER = "Gaia/GAIA3.G"
GAIA_G_FILTER_NAME = "Gaia G"
GAIA_G_MAG_SYS = "Vega"
GAIA_G_EFFECTIVE_WAVELENGTH = 673.0e-9
GAIA_G_ZP_FLUX = 3.64e-9
GAIA_G_ZP_FLUX_UNIT = "Jy"
GAIA_G_ZP_MAG = 0.0


def normalise_band(band: str) -> str:
    """Validates and normalises a Gaia photometric band code.

    Args:
        band (str): Photometric band identifier (currently ``'G'`` only).

    Returns:
        str: Normalised band code.

    Raises:
        ValueError: If ``band`` is not supported by the template provider.
    """
    normalised = str(band).strip().upper()
    if normalised != GAIA_G_BAND:
        raise ValueError(
            f"Unsupported Gaia band '{band}'. Template provider supports '{GAIA_G_BAND}' only."
        )
    return normalised


def resolve_photcal(band: str = GAIA_G_BAND) -> dict:
    """Builds serialisable ``metadata['photcal']`` for a Gaia lightcurve band.

    Args:
        band (str): Photometric band identifier.

    Returns:
        dict: PhotCal GROUP fields for VO export and CurveDash bridge metadata.
    """
    normalise_band(band)
    return {
        PHOTCAL_KEY_FILTER_IDENTIFIER: GAIA_G_FILTER_IDENTIFIER,
        PHOTCAL_KEY_EFFECTIVE_WAVELENGTH: float(GAIA_G_EFFECTIVE_WAVELENGTH),
        PHOTCAL_KEY_EFFECTIVE_WAVELENGTH_UNIT: "m",
        PHOTCAL_KEY_FILTER_NAME: GAIA_G_FILTER_NAME,
        PHOTCAL_KEY_ZP_FLUX: GAIA_G_ZP_FLUX,
        PHOTCAL_KEY_ZP_FLUX_UNIT: GAIA_G_ZP_FLUX_UNIT,
        PHOTCAL_KEY_ZP_MAG: GAIA_G_ZP_MAG,
        PHOTCAL_KEY_ZP_MAG_UNIT: "mag",
        PHOTCAL_KEY_MAG_SYS: GAIA_G_MAG_SYS,
    }


def format_source_name(source_id: int | str) -> str:
    """Formats a Gaia ``source_id`` for display in catalog tables.

    Args:
        source_id (int or str): Gaia DR3 source identifier.

    Returns:
        str: Human-readable object label.
    """
    return f"Gaia DR3 {source_id}"


def build_fetch_votable_kwargs(
    *,
    source_id: int | str,
    ra_deg: float,
    dec_deg: float,
    band: str = GAIA_G_BAND,
) -> dict:
    """Builds keyword arguments for Gaia template VOTable emission.

    Args:
        source_id (int or str): Gaia DR3 source identifier.
        ra_deg (float): ICRS right ascension in degrees.
        dec_deg (float): ICRS declination in degrees.
        band (str): Photometric band code.

    Returns:
        dict: Keyword arguments for ``write_vo_lightcurve``.
    """
    band = normalise_band(band)
    photcal = resolve_photcal(band)
    target_label = format_source_name(source_id)
    description = (
        f"Gaia DR3 epoch photometry template for source {source_id}. "
        f"Filter band: {band}. "
        f"``obs_time`` is Modified Julian Date (MJD = JD - {JD_TO_MJD}). "
        "This dataset is generated by the mock provider for UI development."
    )

    return {
        "table_name": f"GaiaDR3_{sanitize_filename(str(source_id))}_{band}",
        "filter_identifier": photcal[PHOTCAL_KEY_FILTER_IDENTIFIER],
        "filter_name": photcal[PHOTCAL_KEY_FILTER_NAME],
        "refposition": GAIA_REFPOSITION,
        "timescale": GAIA_TIMESCALE,
        "timeorigin": JD_TO_MJD,
        "votable_description": description,
        "table_description": description,
        "creator": GAIA_PIPELINE,
        "zero_point_flux": photcal[PHOTCAL_KEY_ZP_FLUX],
        "zero_point_flux_unit": photcal[PHOTCAL_KEY_ZP_FLUX_UNIT],
        "zero_point_ref_mag": photcal[PHOTCAL_KEY_ZP_MAG],
        "zero_point_ref_mag_unit": photcal[PHOTCAL_KEY_ZP_MAG_UNIT],
        "magnitude_system": photcal[PHOTCAL_KEY_MAG_SYS],
        "effective_wavelength": photcal[PHOTCAL_KEY_EFFECTIVE_WAVELENGTH],
        "effective_wavelength_unit": photcal[PHOTCAL_KEY_EFFECTIVE_WAVELENGTH_UNIT],
        "ra": ra_deg,
        "dec": dec_deg,
        "binary": True,
    }
