version: 1
include: _defaults.yaml

study:
  label: "NSV 807 sector 97 FFI, oriinal template"
  template_dir: ../../data/runs/NSV_807_97_ffi_main/pieces/1
  output_dir: ../../data/runs/NSV_807_97_ffi_main/epoch_spike

export_template:
  method: kvw
